name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Scala and SBT
        uses: olafurpg/setup-scala@v13
        with:
          java-version: 'adopt@1.11'  # or match your actual Java version

      - name: Cache SBT and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: sbt-${{ runner.os }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Run tests
        run: sbt test

      # - name: Publish artifacts (commented out)
      #   env:
      #     SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      #     SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      #     PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      #     PGP_SECRET: ${{ secrets.PGP_SECRET }}
      #   run: |
      #     echo "$PGP_SECRET" | base64 --decode > /tmp/pgp.key
      #     gpg --import /tmp/pgp.key
      #     sbt clean +publishSigned sonatypeBundleRelease
